# Generated by Django 3.0.5 on 2021-02-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='companyStreetName',
        ),
        migrations.RemoveField(
            model_name='company',
            name='companyStreetNumber',
        ),
        migrations.AddField(
            model_name='company',
            name='companyAddress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
