# Generated by Django 3.0.5 on 2021-02-10 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carCurrentlyLeased',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='privateLease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaseStartDate', models.DateField()),
                ('leaseEndDate', models.DateField()),
                ('leaseDownpayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaseMonthlyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaseCar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Car')),
                ('leaseCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
