# Generated by Django 3.0.4 on 2021-02-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='carImage',
            field=models.ManyToManyField(to='main.CarImage'),
        ),
    ]
