# Generated by Django 3.0.5 on 2021-02-15 11:04

import builtins
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20210212_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=50)),
                ('companyStreetName', models.CharField(max_length=100)),
                ('companyStreetNumber', models.IntegerField()),
                ('companyCity', models.CharField(max_length=20)),
                ('companyPostalCode', models.IntegerField()),
                ('cvrNumber', models.IntegerField(verbose_name=builtins.max)),
                ('contactPerson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='carCurrentlyLeased',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePhoneNumber', models.DecimalField(decimal_places=0, max_digits=8)),
                ('profileCprNumber', models.DecimalField(decimal_places=0, max_digits=10)),
                ('profileStreetName', models.CharField(max_length=50)),
                ('profileStreetNumber', models.IntegerField()),
                ('profileStreetNumberSuffix', models.CharField(max_length=10)),
                ('profileCity', models.CharField(max_length=50)),
                ('profilePostalCode', models.IntegerField()),
                ('profileUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivateLease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaseStartDate', models.DateField()),
                ('leaseEndDate', models.DateField()),
                ('leaseDownpayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaseMonthlyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaseCar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Car')),
                ('leaseCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyLease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaseStartDate', models.DateField()),
                ('leaseEndDate', models.DateField()),
                ('leaseDownpayment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaseMonthlyPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('leaseCar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Car')),
                ('leaseCustomerCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Company')),
            ],
        ),
    ]
