# Generated by Django 3.0.4 on 2021-02-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210223_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='carReadyForBusinessLeasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='carReadyForPrivateLeasing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='car',
            name='carNewPrice',
            field=models.IntegerField(default=1),
        ),
    ]
