# Generated by Django 3.0.5 on 2021-02-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210215_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileStreetName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileStreetNumber',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profileStreetNumberSuffix',
        ),
        migrations.AddField(
            model_name='companylease',
            name='contract',
            field=models.FileField(default=1, upload_to='contracts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='privatelease',
            name='contract',
            field=models.FileField(default=1, upload_to='contracts'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profileAddress',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
